### ISSUE TITLE
bug ssl update

### ISSUE THREAD

**Issue by SiNaPsEr0x** [HelloZeroNet/ZeroNet-mac#1]
Step 1: Please describe your environment

ZeroNet version: 0.6.4 rev3703
Operating system: macOS 10.14.3
Web browser: firefox or safari
Tor status: /always/
Opened port: no
Special configuration: ____
Step 2: Describe the problem:

```
[](Downloading from: https://github.com/HelloZeroNet/ZeroNet/archive/master.zip Error downloading update from https://github.com/HelloZeroNet/ZeroNet/archive/master.zip: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)
Downloading from: https://gitlab.com/HelloZeroNet/ZeroNet/repository/archive.zip?ref=master Error downloading update from https://gitlab.com/HelloZeroNet/ZeroNet/repository/archive.zip?ref=master: EOF occurred in violation of protocol (_ssl.c:661)
Downloading from: https://try.gogs.io/ZeroNet/ZeroNet/archive/master.zip Error downloading update from https://try.gogs.io/ZeroNet/ZeroNet/archive/master.zip: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)
Update error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661))
```
Steps to reproduce:

updating problem with sslv1

but on update manually this error:

SiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core
$ python2 update.py 
```
Update site path: /Users/SiNaPsE/Library/Application Support/ZeroNet/data/1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp, bad_files: 0
Downloading from: https://github.com/HelloZeroNet/ZeroNet/archive/master.zip . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Downloaded.
Plugins enabled: ['Sidebar', 'ContentFilter', 'Bigfile', 'MergerSite', 'CryptMessage', 'Chart', 'Trayicon', 'FilePack', 'OptionalManager', 'UiConfig', 'TranslateSite', 'PeerDb', 'AnnounceLocal', 'Cors', 'AnnounceShare', 'Stats', 'Zeroname', 'AnnounceZero', 'Newsfeed'] disabled: ['DonationMessage', 'Dnschain', 'Zeroname-local', 'StemPort', 'UiPassword', 'Bootstrapper', 'Multiuser']
Extracting to /Applications/ZeroNet.app/Contents/Resources/core... . . . . . . . . . . . . . . . . . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Done.
Press enter to exit

SiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core
$ /Applications/ZeroNet.app/Contents/MacOS/ZeroNet 
- Starting ZeroNet...
ERROR:root:Unhandled exception: signal only works in main thread
Traceback (most recent call last):
  File "/Applications/ZeroNet.app/Contents/Resources/core/zeronet.py", line 16, in main
ValueError: signal only works in main thread
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 801, in __bootstrap_inner
  File "threading.pyo", line 754, in run
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 157, in main
  File "/Applications/ZeroNet.app/Contents/Resources/core/zeronet.py", line 56, in main
ImportError: No module named Config

^CTraceback (most recent call last):
  File "/Applications/ZeroNet.app/Contents/Resources/__boot__.py", line 81, in <module>
    _run()
  File "/Applications/ZeroNet.app/Contents/Resources/__boot__.py", line 66, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 179, in <module>
    gui()
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 106, in gui
    time.sleep(0.1)
KeyboardInterrupt
2019-02-01 16:11:58.506 ZeroNet[26769:266104] ZeroNet Error
2019-02-01 16:11:58.506 ZeroNet[26769:266104] ZeroNet Error
```

SiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core
$

**Comment by SiNaPsEr0x** [comment]
I fix with download unix version from [and:](url
https://github.com/HelloZeroNet/ZeroNet/archive/master.zip)
I've completed the first three steps, the above is what happens when I try to complete the last step.
Install Homebrew
brew install python
pip install gevent msgpack-python
Download, Unpack, run python2 zeronet.py (from the other version is updated to python3)

**Comment by HelloZeroNet** [comment]
Thanks for reporting I have just fixed the "ERROR:root:Unhandled exception: signal only works in main thread" problem in Rev3852 + fixed Safari compatibility

The update over https problem fix is still pending until the first Python3 release
